name: neighbour_app
description: A flutter template.
version: 1.1.8+26
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  amplify_auth_cognito: ^1.6.0
  amplify_flutter: ^1.6.0
  bloc: ^8.1.2
  connectivity_plus: ^5.0.0
  cupertino_icons: ^1.0.6
  dio: ^5.3.3
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  expandable_bottom_sheet: ^1.1.1+1
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_flip_card: ^0.0.4
  flutter_local_notifications: ^16.2.0
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^3.0.1
  flutter_stripe: ^9.5.0+1
  flutter_svg: ^2.0.6
  flutter_svg_provider: ^1.0.4
  font_awesome_flutter: ^10.5.0
  geocoder2: ^1.4.0
  geocoding: ^2.1.1
  geolocator: ^7.7.0
  get_it: ^7.6.4
  glassmorphism_ui: ^0.3.0
  go_router: ^11.1.3
  google_maps_flutter: ^2.5.0
  html: ^0.15.4
  image_picker: ^1.0.4
  intl: ^0.18.0
  json_annotation: ^4.8.1
  path: ^1.8.3
  permission_handler: ^11.0.1
  pie_chart: ^5.3.2
  pin_code_fields: ^8.0.1
  retrofit: ^4.0.3
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  sizer: ^2.0.15
  skeletons: ^0.0.3
  syncfusion_flutter_core: ^22.2.12
  syncfusion_flutter_sliders: ^22.2.12
  timeago: ^3.6.1
  timeline_tile: ^2.0.0
  url_launcher: ^6.1.14
  uuid: ^4.2.2
  web_socket_channel: ^2.4.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: ^2.3.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8
  very_good_analysis: ^5.0.0

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icons/logo.png"
  android: true
  ios: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app-icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/app-icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/app-icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/app-icon.png"

flutter:
  assets:
    - .env.dev
    - .env.staging
    - .env.production
    - assets/images/
    - assets/fonts/
    - assets/svgs/
    - assets/icons/

  fonts:
    - family: InterRegular
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
    - family: InterMedium
      fonts:
        - asset: assets/fonts/inter/Inter-Medium.ttf
    - family: InterSemibold
      fonts:
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
    - family: InterBold
      fonts:
        - asset: assets/fonts/inter/Inter-Bold.ttf
    - family: RalewaySemibold
      fonts:
        - asset: assets/fonts/raleway/Raleway-SemiBold.ttf
    - family: RalewayExtrabold
      fonts:
        - asset: assets/fonts/raleway/Raleway-ExtraBold.ttf
    - family: NunitoNormal
      fonts:
        - asset: assets/fonts/nunito/Nunito-Medium.ttf
    - family: RalewayBold
      fonts:
        - asset: assets/fonts/raleway/Raleway-Bold.ttf
    - family: RalewayMedium
      fonts:
        - asset: assets/fonts/raleway/Raleway-Medium.ttf
    - family: UrbanistMedium
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Medium.ttf
    - family: UrbanistSemiBold
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-SemiBold.ttf
    - family: UrbanistBold
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Bold.ttf

  uses-material-design: true
